config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contactus", to: "pages#contactus"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  resources :experiences do
    resources :bookings, only: [:new, :create, :show, :index, :edit, :update]
    resources :bookings, only: [:destroy], as: :booking_destroy
  end

  resources :bookings do
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :experience
  belongs_to :user
  has_many :reviews, dependent: :destroy

  def review_present?
    review.present?
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :experience

  validates :content, presence: true
  validates :user_name, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_no])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_no])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_experience, only: %i[new create show edit update destroy]

  def index
    @bookings = policy_scope(Booking.where(user_id: current_user))
    @myhostings = policy_scope(Booking.joins(:experience).where(experience: { user_id: current_user.id }))
  end

  def show
    @booking = Booking.find(params[:id])
    authorize(@booking)
  end

  def new
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new
    authorize(@booking)
  end

  def create
    @booking = Booking.new(booking_params)
    #number of bookings with the experience and sum of the pax
    #if capacity < number_of_pax + (existing bookings pax) => fail
    #aggregate function
    @booking.user = current_user
    @booking.user_name = "#{current_user.first_name} #{current_user.last_name}"
    @booking.experience = @experience
    @booking.status = "Pending"

    authorize(@booking)

    if @booking.save!
      redirect_to experience_booking_path(@experience, @booking), notice: "Booking was successfully placed."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize(@booking)
  end

  def update
    @booking = Booking.find(params[:id])
    authorize(@booking)
    if @booking.update(booking_params)
      redirect_to experience_booking_path(@experience, @booking), notice: "Booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize(@booking)
    @booking.destroy
    redirect_to experience_path(@experience), notice: "Booking was successfully destroyed."
  end

  private

  def set_experience
    @experience = Experience.find(params[:experience_id])
  end

  def booking_params
    params.require(:booking).permit(:booking_date, :number_of_pax, :comment, :status, :completed)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy ]

  def index
    @experiences = policy_scope(Experience)
  end

  def show
    @experience = Experience.find(params[:id])
    @bookings = @experience.bookings
    @reviews = Review.where(booking_id: @bookings.pluck(:id))
    @booking = Booking.new
  end

  def new
    @experience = Experience.new
    authorize(@experience)
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user

    authorize(@experience)

    if @experience.save!
      redirect_to experience_path(@experience), notice: "Experience was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @experience.update(experience_params)
      redirect_to experience_path(@experience), notice: "Experience was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @experience.destroy
    redirect_to experiences_path, notice: "Experience was successfully destroyed."
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
    authorize(@experience)
  end

  def experience_params
    params.require(:experience).permit(:name, :description, :price, :capacity, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    # code to display all reviews for an experience or a booking
  end

  def show
    @booking = Booking.find(params[:booking_id])
    authorize(@review)
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @experience = Experience.find(@booking.experience_id)
    @review = @booking.reviews.build
    authorize(@review)
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @experience = Experience.find(@booking.experience_id)
    @review = @booking.reviews.build(review_params)
    if @booking.user != current_user
      redirect_to @booking, alert: "You are not authorized to leave a review for this booking."
      return
    end

    @review.user_name = @booking.user_name
    @review.experience = @experience

    authorize(@review)

    if @review.save
      redirect_to experience_booking_path(@experience, @booking), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:booking_id])
    authorize(@review)
  end

  def update
    authorize(@review)
    if @review.update(review_params)
      redirect_to experience_booking_path(@review.experience_id, @review.booking_id), notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @review.booking, notice: 'Review was successfully destroyed.'
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Name:</strong>
    <%= booking.experience.name %>
  </p>

   <p>
    <strong>Description:</strong>
    <%= booking.experience.description %>
  </p>

   <p>
    <strong>Price:</strong>
    <%= booking.experience.price %>
  </p>

  <p>
    <strong>User:</strong>
    <%= booking.user_name %>
  </p>

  <p>
    <strong>Booking Date:</strong>
    <%= booking.booking_date %>
  </p>

  <p>
    <strong>Number of Pax:</strong>
    <%= booking.number_of_pax %>
  </p>

  <p>
    <strong>Booking Status:</strong>
    <%= booking.status %>
  </p>

    <p>
    <strong>Comment:</strong>
    <%= booking.comment %>
  </p>

</div>

app/views/bookings/_form.html.erb
<div class="centered-form">
<%= simple_form_for([experience, booking]) do |f| %>

  <div class="form-inputs">
    <%= f.input :booking_date, as: :date %>
  </div>

  <div class="form-inputs">
    <%= f.input :number_of_pax, as: :integer %>
  </div>

  <div class="form-inputs">
  <%= f.text_field :comment, placeholder: "Add a comment" %>
  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class: "btn btn-success", onclick: "console.log('submit button clicked')" %>
  </div>

<% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Editing experience</h1>

<%= render "form", experience: @experience, booking: @booking %>

<br>

<div>
  <%= link_to "Show this experience", experience_path(@experience) %> |
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/bookings/index.html.erb
<h1 class="text-black"><%="#{current_user.first_name} #{current_user.last_name}"%></h1>
<h3 class="text-black">These are your bookings</h3>

<% counter = 1 %>
<% @bookings.each do |booking| %>
  <div>
    <h3>Booking <%= counter %></h3>
    <p><strong>Experience Name:</strong> <%= booking.experience.name %></p>
    <p><strong>Booking Date:</strong> <%= booking.booking_date %></p>
    <p><strong>Number of Pax:</strong> <%= booking.number_of_pax %></p>
    <p><strong>Booking Status:</strong> <%= booking.status %></p>
  </div>
  <% counter += 1 %>
  <%= link_to "Show this booking", experience_booking_path(booking.experience, booking), class: "btn btn-primary" if policy(booking).show? %>
<% end %>

<h3 class="text-black">These are your experience's bookings</h3>

<% counter = 1 %>
<% @myhostings.each do |booking| %>
  <div>
    <h3>Booking <%= counter %></h3>
    <p><strong>Booking Id:</strong> <%= booking.id %></p>
    <p><strong>Experience Name:</strong> <%= booking.experience.name %></p>
    <p><strong>User Name:</strong> <%= booking.user_name %></p>
    <p><strong>Booking Date:</strong> <%= booking.booking_date %></p>
    <p><strong>Number of Pax:</strong> <%= booking.number_of_pax %></p>
    <p><strong>Booking Status:</strong> <%= booking.status %></p>
    <p><strong>Comment:</strong> <%= booking.comment %></p>
  </div>
  <%= link_to "Show this booking", experience_booking_path(booking.experience, booking), class: "btn btn-primary" if policy(booking).show? %>
  <%# <%= link_to "Destroy this booking", experience_booking_destroy_path(booking.experience, booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} if policy(booking).destroy? %>
  <% counter += 1 %>

<% end %>




<%# add a button to look into each booking %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", experience: @experience, booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<h1> Hi, thank you for booking! Please check out.</h1>
  <div class="col-25">
    <div class="container">
      <h4>Cart
        <span class="price" style="color:black">
        </span>
      </h4>
<%= render @booking %>
      <hr>
    </div>
  </div>
<div>
  <% if !@booking.completed || Date.today < @booking.booking_date %>
    <% if @booking.status == "Pending"%>
      <%= link_to "Edit your booking", edit_experience_booking_path(@experience, @booking) if policy(@booking).edit? %>
      <% if policy(@booking).status? %>
        <%= form_with url: [@experience, @booking], method: :patch do |form| %>
          <%= form.text_field :comment, placeholder: "Add a comment", name: "booking[comment]" %>
          <%= form.submit "Confirm the booking", class: "btn btn-primary", name: "booking[status]", value: "Confirmed" %>
        <% end %>
      <% end %>
        <% if policy(@booking).status? %>
        <%= form_with url: [@experience, @booking], method: :patch do |form| %>
          <%= form.text_field :comment, placeholder: "Add a comment", name: "booking[comment]" %>
          <%= form.submit "Reject the booking", class: "btn btn-primary", name: "booking[status]", value: "Rejected" %>
        <% end %>
      <% end %>
      <%= link_to "View other experiences", experiences_path %>
      <%= link_to "Cancel your booking", experience_booking_destroy_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} if policy(@booking).destroy? %>
    <% elsif @booking.status == "Confirmed" %>
      <%= link_to "View other experiences", experiences_path %>
      <%= button_to "Request for cancellation", [@experience, @booking], params: {booking: {comment: "Cancellations Requested"}}, method: :patch if policy(@booking).edit? %>
      <%= button_to "Approve cancellation", [@experience, @booking], params: {booking: {status: "Cancelled"}}, method: :patch if policy(@booking).status? if @booking.comment == "Cancellations Requested"%>
      <% if @booking.status == "Confirmed" && !@booking.completed %>
        <%= button_to "Mark as completed", [@experience, @booking], params: {booking: {completed: true, status: "Completed"}}, method: :patch if policy(@booking).status? %>
      <% end %>
    <% elsif @booking.status == "Rejected" %>
      <%= link_to "View other experiences", experiences_path %>
    <% elsif @booking.status == "Cancelled" %>
      <%= link_to "View other experiences", experiences_path %>
    <% else %>
      <%= link_to "View other experiences", experiences_path %>
      <%# the cancel your booking is for cleaning data purposes, user is only allowed to cancel the booking when the booking is pending %>
      <%= link_to "Cancel your booking", experience_booking_destroy_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} if policy(@booking).destroy? %>
    <% end %>
  <% elsif @booking.completed && Date.today > @booking.booking_date %>
    <% if !@booking.reviews.present?%>
      <%= link_to "Leave a review", new_booking_review_path(@booking) %>
    <% end %>
    <%= link_to "Book other experiences", experiences_path %>
    <% if @booking.reviews.present? %>
      <%= link_to "View review", booking_review_path(@booking, @booking.reviews.first) %>
      <%# <%= link_to "Edit review", edit_experience_booking_review_path(@experience, @booking, @review) if policy(@review).update? %>
    <% end %>
  <% else %>
    <%= link_to "Book other experiences", experiences_path %>
  <% end %>
</div>

<div class="col-25">

    <div class="col-25">
    <div class="container">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="johndoe@gmail.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="Bugis 101010">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="Singapore">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

    <div class="col-25">
    <div class="container">
            <h3>Payment</h3>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">

            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
                <label>
        <div class="col-md-12">
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
        <input type="submit" value="Continue to checkout" class="btn btn-danger">
        </div>
      </form>
              </div>

app/views/experiences/_experience.html.erb
<div id="<%= dom_id experience %>">
  <p>
    <strong>Name:</strong>
    <%= experience.name %>
  </p>
   <p>
    <strong>Description:</strong>
    <%= experience.description %>
  </p>
   <p>
    <strong>Price: $</strong>
    <%= experience.price %>0
  </p>
<%# Username %>
  <p>
    <%# <strong>User:</strong>
    <%= experience.user.email %>
  </p>
</div>

app/views/experiences/_form.html.erb
<div class="centered-form">
<%= simple_form_for(@experience) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.input :price %>
  </div>

  <div class="form-inputs">
    <%= f.input :capacity %>
  </div>

   <div class="form-inputs">
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,class: "btn-success" %>
  </div>

<% end %>
</div>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Show this experience", @experience %> |
  <%= link_to "Back to experiences", experiences_path %>
</div>

app/views/experiences/index.html.erb
<div class="bg-image">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3 text-center">
        <p class="text-success"><%= notice %></p>
        <h1 class="text-black">Hello <%=current_user.first_name%>!</h1>
          <h3 class="text-black">Start to host a new experience</h3>
          <p>What’s an experience?</p>
          <p>It’s an activity that goes beyond the typical tour or class, designed and led by locals all over the world. Show off your city, craft, cause, or culture by hosting an experience.</p>
        </div>
      </div>
    </div>
  </div>
<div>
<div id="experiences" class="row mt-5">
  <% @experiences.each do |experience| %>
  <br>
    <div class="col-md-4 mb-4">
      <% experience.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <p>
        <br>
        <%= link_to "Show this experience", experience, class: "btn btn-primary" %>
      </p>
      <%= render experience %>
      <% end %>
      <br>
    </div>
  <% end %>
    </div>
</div>

app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render "form", experience: @experience %>

<br>

<div>
  <%= link_to "Back", experiences_path, class: "btn btn-outline-primary" %>
</div>

app/views/experiences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @experience %>

<% @experience.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<h2>Reviews</h2>
<% if @reviews.present? %>
  <% @reviews.each do |review| %>
    <div class="review">
      <p><strong>User Name:</strong> <%= review.user_name %></p>
      <p><strong>Rating:</strong> <%= review.rating %></p>
      <p><strong>Content:</strong> <%= review.content %></p>
      <%# <p><%= link_to "Edit", edit_booking_review_path(@booking, review) %></p>
      <%# <p><%= link_to "Delete", booking_review_path(@booking, review), method: :delete, data: { confirm: "Are you sure you want to delete this review?" } %></p>
    </div>
  <% end %>
<% else %>
  <p>No reviews yet.</p>
<% end %>

<div>
  <% if policy(@experience).edit? %>
    <%= link_to "Edit this experience", edit_experience_path(@experience) %>
  <% end %>
  <%= link_to "Back to experiences", experiences_path %>
  <%= button_to "Destroy this experience", @experience, method: :delete if policy(@experience).destroy? %>
</div>

<h1>New booking</h1>
<%= simple_form_for [@experience, @booking] do |f| %>
  <%= f.input :booking_date %>
  <%= f.input :number_of_pax %>
  <%= f.input :comment, placeholder: "Add a comment" %>
  <%= f.submit "Submit booking", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbExperiencesTogather</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>


  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <% if user_signed_in?%>
    <%# to show the user email %>
      <%# <h2> Hi <%= current_user.email %>
    <% end %>
  </body>
</html>

app/views/pages/contactus.html.erb
<head>
  <title>Contact Us</title>
  <%= stylesheet_link_tag '/app/assets/stylesheets/contactus/_contactus.scss', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<div class="container mt-5">
  <h1 class="mb-5">Contact Us</h1>

  <div class="row">
    <div class="col-12 col-md-8">
      <img src="https://img.freepik.com/free-photo/happy-hipster-company-friends-traveling-around-world_285396-3653.jpg?w=900&t=st=1678281211~exp=1678281811~hmac=6404c7c632c6ee47f41be1378be58f589ec6dcb9352dc3b54ae3717732ae6551" class="img-fluid">
    </div>
    <div class="col-6 col-md-4">
      <div class="contactinfo">
        <p>Please feel free to contact us using the information below:</p>

        <ul>
          <li><i class="fas fa-envelope"></i> Email: hello@airbnb.com</li>
          <li><i class="fas fa-phone"></i> Phone: +65 6888 6888</li>
          <li><i class="fas fa-map-marker-alt"></i> Address: 290 Orchard Road 18-03 The Paragon</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@booking, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <%= f.submit "Update Review", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Cancel', booking_review_path(@booking, @review) %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<h1>New review</h1>
<%= simple_form_for [@experience, @booking, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Review</h1>

<p><strong>Rating:</strong> <%= @review.rating %></p>
<p><strong>Description:</strong> <%= @review.content %></p>
<p><strong>User:</strong> <%= @review.user_name %></p>

<%= link_to 'Edit', edit_booking_review_path(@booking, @review) %>
<%= link_to 'Back', experience_booking_path(@review.experience_id, @booking) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="https://seeklogo.com/images/A/airbnb-logo-1D03C48906-seeklogo.com.png" width="30" height="30" alt="">
  </a>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <%# <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> %>

</li>

 <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Contact Us", contactus_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Experiences", experiences_path, class: "dropdown-item" %>
              <%= link_to "Host An Experience", new_experience_path, class: "dropdown-item" %>
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <li class="nav-item active">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Contact Us", contactus_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Experiences", experiences_path, class: "dropdown-item" %>
              <%= link_to "Host An Experience", new_experience_path, class: "dropdown-item" %>
            </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>
</nav>